/*  BC2000DL — Preset data definitions.

    43 presets in 7 categories, plus FACTORY (idx 0).
    All values validated at authoring time:
      mic_gain >= 0.5, master >= 0.75, drive >= 0.5, wow <= 2.0
*/

#include "Presets.h"

namespace bc2000dl
{
    // ------------------------------------------------------------------
    // Category list (displayed in browser left column)
    // ------------------------------------------------------------------
    const char* const kCategories[kNumCategories] = {
        "ALL",
        "TAPE COLOR",
        "VOCALS",
        "DRUMS",
        "BASS",
        "SYNTH",
        "BROADCAST",
        "SPECIAL",
    };

    // ------------------------------------------------------------------
    // Preset table
    // Fields use designated initializers — any omitted field takes the
    // default value declared in PresetData (mic_gain=0.5, master=0.85 …)
    // ------------------------------------------------------------------
    const PresetData kPresets[kNumPresets] = {

        // ============================================================
        // idx 0 — FACTORY  (all defaults, full reset)
        // ============================================================
        {
            .name     = "FACTORY",
            .category = "ALL",
            .tip      = "Factory defaults — neutral reference state",
        },

        // ============================================================
        // TAPE COLOR  (idx 1–7)
        // ============================================================
        {
            .name     = "AGFA ARCHIVE",
            .category = "TAPE COLOR",
            .tip      = "Agfa ferric at 19 IPS — open, natural archive character",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.15f,
            .saturation_drive_r = 1.15f,
            .wow_flutter    = 0.2f,
        },
        {
            .name     = "BASF SATURATION",
            .category = "TAPE COLOR",
            .tip      = "BASF at 9.5 IPS — warm saturation with subtle low-end lift",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.65f,
            .saturation_drive_r = 1.65f,
            .bias_amount    = 0.9f,
            .wow_flutter    = 0.4f,
            .bass_db        = 1.5f,
        },
        {
            .name     = "SCOTCH REFERENCE",
            .category = "TAPE COLOR",
            .tip      = "Scotch Type 150 at 19 IPS — bright, open, reference-grade",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.05f,
            .saturation_drive_r = 1.05f,
            .bias_amount    = 1.05f,
            .wow_flutter    = 0.15f,
            .treble_db      = 0.8f,
        },
        {
            .name     = "SLOW SPEED WARMTH",
            .category = "TAPE COLOR",
            .tip      = "Agfa at 4.75 IPS — thick saturation, heavy wow, cassette soul",
            .tape_formula   = 0,
            .speed          = 0,
            .saturation_drive   = 1.85f,
            .saturation_drive_r = 1.85f,
            .bias_amount    = 0.78f,
            .wow_flutter    = 1.2f,
            .bass_db        = 2.0f,
        },
        {
            .name     = "9.5 MUSICAL",
            .category = "TAPE COLOR",
            .tip      = "Agfa at 9.5 IPS — classic studio speed, musical saturation",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.35f,
            .saturation_drive_r = 1.35f,
            .bias_amount    = 0.95f,
            .wow_flutter    = 0.45f,
        },
        {
            .name     = "BASF HIGH BIAS",
            .category = "TAPE COLOR",
            .tip      = "BASF over-biased at 19 IPS — extra warmth, rolled-off top end",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.45f,
            .saturation_drive_r = 1.45f,
            .bias_amount    = 1.2f,
            .bass_db        = 1.0f,
            .treble_db      = -0.5f,
        },
        {
            .name     = "AGFA '70s",
            .category = "TAPE COLOR",
            .tip      = "70s studio pop tape — forward mids, warm body, gentle wow",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.55f,
            .saturation_drive_r = 1.55f,
            .wow_flutter    = 0.5f,
            .bass_db        = 1.0f,
            .treble_db      = 0.5f,
        },

        // ============================================================
        // VOCALS  (idx 8–13)
        // ============================================================
        {
            .name     = "VOCAL SILK",
            .category = "VOCALS",
            .tip      = "Smooth vocal — gentle saturation tames harshness",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.25f,
            .saturation_drive_r = 1.25f,
            .treble_db      = -0.5f,
        },
        {
            .name     = "VOCAL WARMTH",
            .category = "VOCALS",
            .tip      = "Vintage warm vocal — BASF body with slight bass lift",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.35f,
            .saturation_drive_r = 1.35f,
            .bass_db        = 1.0f,
            .treble_db      = -0.3f,
        },
        {
            .name     = "VOCAL AIR",
            .category = "VOCALS",
            .tip      = "Hi-fi female vocal — Scotch clarity with lifted air",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.1f,
            .saturation_drive_r = 1.1f,
            .treble_db      = 1.2f,
        },
        {
            .name     = "VOCAL DOUBLES",
            .category = "VOCALS",
            .tip      = "Natural doubling feel — subtle wow creates pitch micro-shift",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.2f,
            .saturation_drive_r = 1.2f,
            .bias_amount    = 0.95f,
            .wow_flutter    = 0.8f,
        },
        {
            .name     = "CROONER",
            .category = "VOCALS",
            .tip      = "Warm vintage male vocal — BASF at 9.5 IPS, bass-forward",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.4f,
            .saturation_drive_r = 1.4f,
            .bass_db        = 1.5f,
            .treble_db      = -0.3f,
        },
        {
            .name     = "SOPRANO",
            .category = "VOCALS",
            .tip      = "Clean delicate vocal — Scotch sparkle with minimal saturation",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.05f,
            .saturation_drive_r = 1.05f,
            .wow_flutter    = 0.2f,
            .treble_db      = 0.5f,
        },

        // ============================================================
        // DRUMS  (idx 14–19)
        // ============================================================
        {
            .name     = "DRUM BUS GLUE",
            .category = "DRUMS",
            .tip      = "Gentle bus glue — BASF at 19 IPS, natural drum cohesion",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.45f,
            .saturation_drive_r = 1.45f,
            .bias_amount    = 0.95f,
            .bass_db        = 1.0f,
        },
        {
            .name     = "DRUM SMASH",
            .category = "DRUMS",
            .tip      = "Aggressive punch — hard saturation on snare and kick",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.8f,
            .saturation_drive_r = 1.8f,
            .bias_amount    = 0.85f,
            .bass_db        = 2.0f,
            .treble_db      = 1.0f,
        },
        {
            .name     = "JAZZ KIT",
            .category = "DRUMS",
            .tip      = "Warm natural acoustic drums — Agfa at 9.5 IPS",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.3f,
            .saturation_drive_r = 1.3f,
            .bass_db        = 1.5f,
            .treble_db      = -0.5f,
        },
        {
            .name     = "TRANSIENT ROUND",
            .category = "DRUMS",
            .tip      = "Tape rounding for heavy hits — BASF at 9.5 IPS, soft attack",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.7f,
            .saturation_drive_r = 1.7f,
            .bias_amount    = 0.8f,
            .wow_flutter    = 0.4f,
        },
        {
            .name     = "SNAP & CRACK",
            .category = "DRUMS",
            .tip      = "Tight transient-forward — Scotch at 19 IPS, cracking snare",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.25f,
            .saturation_drive_r = 1.25f,
            .bias_amount    = 1.05f,
            .treble_db      = 1.0f,
        },
        {
            .name     = "KICK WEIGHT",
            .category = "DRUMS",
            .tip      = "Heavy low-end on kick — deep bass lift with tape compression",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.4f,
            .saturation_drive_r = 1.4f,
            .bias_amount    = 0.9f,
            .bass_db        = 3.5f,
        },

        // ============================================================
        // BASS  (idx 20–24)
        // ============================================================
        {
            .name     = "BASS WEIGHT",
            .category = "BASS",
            .tip      = "Deep rich bass — maximum body, rolled-off top",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.45f,
            .saturation_drive_r = 1.45f,
            .bass_db        = 4.0f,
            .treble_db      = -0.5f,
        },
        {
            .name     = "SYNTH BASS",
            .category = "BASS",
            .tip      = "Tight electronic bass — Scotch definition with punch",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.3f,
            .saturation_drive_r = 1.3f,
            .bass_db        = 2.0f,
            .treble_db      = 0.5f,
        },
        {
            .name     = "SUB PUSH",
            .category = "BASS",
            .tip      = "Extreme sub-bass — Agfa at 4.75 IPS, maximum rumble",
            .tape_formula   = 0,
            .speed          = 0,
            .saturation_drive   = 1.6f,
            .saturation_drive_r = 1.6f,
            .bias_amount    = 0.85f,
            .bass_db        = 5.0f,
        },
        {
            .name     = "BASS HARMONIC",
            .category = "BASS",
            .tip      = "Harmonic richness on bass — BASF under-biased for odd harmonics",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.75f,
            .saturation_drive_r = 1.75f,
            .bias_amount    = 0.8f,
            .bass_db        = 1.5f,
        },
        {
            .name     = "FRETLESS WARM",
            .category = "BASS",
            .tip      = "Warm fretless character — wow flutter adds natural pitch slide",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.2f,
            .saturation_drive_r = 1.2f,
            .wow_flutter    = 0.5f,
            .bass_db        = 2.5f,
            .treble_db      = -1.0f,
        },

        // ============================================================
        // SYNTH  (idx 25–30)
        // ============================================================
        {
            .name     = "BERG · DEPECHE PAD",
            .category = "SYNTH",
            .tip      = "Dense pad character — BASF echo at 9.5 IPS, bass warmth",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.6f,
            .saturation_drive_r = 1.6f,
            .bass_db        = 2.5f,
            .echo_enabled   = true,
            .echo_amount    = 0.25f,
            .echo_amount_r  = 0.25f,
        },
        {
            .name     = "BERG · DELTA SYNTH",
            .category = "SYNTH",
            .tip      = "Rich synth saturation — Scotch at 19 IPS, extreme drive",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.85f,
            .saturation_drive_r = 1.85f,
            .bias_amount    = 0.85f,
        },
        {
            .name     = "COLDWAVE LEAD",
            .category = "SYNTH",
            .tip      = "Cold metallic synth — Scotch clarity, high-frequency lift",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.15f,
            .saturation_drive_r = 1.15f,
            .bias_amount    = 1.1f,
            .treble_db      = 1.5f,
        },
        {
            .name     = "PAD HEAVEN",
            .category = "SYNTH",
            .tip      = "Lush evolving pads — subtle wow flutter creates slow shimmer",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.2f,
            .saturation_drive_r = 1.2f,
            .wow_flutter    = 0.8f,
            .bass_db        = 1.0f,
            .treble_db      = -0.3f,
        },
        {
            .name     = "PROG ORGAN",
            .category = "SYNTH",
            .tip      = "70s progressive keyboards — Agfa at 9.5 IPS, balanced tone",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.45f,
            .saturation_drive_r = 1.45f,
            .bass_db        = 1.0f,
            .treble_db      = 0.5f,
        },
        {
            .name     = "ELECTRO PULSE",
            .category = "SYNTH",
            .tip      = "Electronic pulse — BASF at 19 IPS, forward mids and presence",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.55f,
            .saturation_drive_r = 1.55f,
            .bass_db        = 1.0f,
            .treble_db      = 1.0f,
        },

        // ============================================================
        // BROADCAST  (idx 31–35)
        // ============================================================
        {
            .name     = "BBC MIDRANGE",
            .category = "BROADCAST",
            .tip      = "Classic BBC broadcast character — warm mids, slight bass cut",
            .tape_formula   = 0,
            .speed          = 2,
            .saturation_drive   = 1.2f,
            .saturation_drive_r = 1.2f,
            .bass_db        = -0.5f,
            .treble_db      = 0.5f,
        },
        {
            .name     = "NAGRA NEUTRAL",
            .category = "BROADCAST",
            .tip      = "Swiss field recorder — clean, transparent, precise wow",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.1f,
            .saturation_drive_r = 1.1f,
            .bias_amount    = 1.05f,
            .wow_flutter    = 0.25f,
        },
        {
            .name     = "BROADCAST FULLRANGE",
            .category = "BROADCAST",
            .tip      = "Wide broadcast presence — BASF clarity with extended top end",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.3f,
            .saturation_drive_r = 1.3f,
            .treble_db      = 0.8f,
        },
        {
            .name     = "VISCONTI '74",
            .category = "BROADCAST",
            .tip      = "Bowie / T.Rex sessions — BASF warmth, low-end authority",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.45f,
            .saturation_drive_r = 1.45f,
            .bass_db        = 1.5f,
        },
        {
            .name     = "KRAFTWERK '78",
            .category = "BROADCAST",
            .tip      = "Kling Klang precision — BASF at 9.5 IPS, measured echo depth",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.3f,
            .saturation_drive_r = 1.3f,
            .echo_enabled   = true,
            .echo_amount    = 0.4f,
            .echo_amount_r  = 0.4f,
        },

        // ============================================================
        // SPECIAL  (idx 36–42)
        // ============================================================
        {
            .name     = "BERG · PROTON CRUNCH",
            .category = "SPECIAL",
            .tip      = "Extreme lo-speed crunch — Scotch at 4.75 IPS, brutal saturation",
            .tape_formula   = 2,
            .speed          = 0,
            .saturation_drive   = 1.95f,
            .saturation_drive_r = 1.95f,
            .bias_amount    = 0.75f,
        },
        {
            .name     = "DUB ECHO",
            .category = "SPECIAL",
            .tip      = "Heavy dub delay — long echo with deep bass for cavernous spaces",
            .tape_formula   = 1,
            .speed          = 2,
            .saturation_drive   = 1.35f,
            .saturation_drive_r = 1.35f,
            .bass_db        = 3.0f,
            .echo_enabled   = true,
            .echo_amount    = 0.7f,
            .echo_amount_r  = 0.7f,
        },
        {
            .name     = "LO-FI POP",
            .category = "SPECIAL",
            .tip      = "Cassette-era lo-fi — 4.75 IPS, heavy wow, generation loss",
            .tape_formula   = 0,
            .speed          = 0,
            .saturation_drive   = 1.9f,
            .saturation_drive_r = 1.9f,
            .wow_flutter    = 1.8f,
            .multiplay_gen  = 4,
        },
        {
            .name     = "CRT NIGHTMARE",
            .category = "SPECIAL",
            .tip      = "Maximum degradation — extreme flutter, crushed bass, multi-gen",
            .tape_formula   = 0,
            .speed          = 0,
            .saturation_drive   = 1.7f,
            .saturation_drive_r = 1.7f,
            .wow_flutter    = 2.0f,
            .multiplay_gen  = 4,
            .bass_db        = 3.0f,
        },
        {
            .name     = "SHOEGAZE WALL",
            .category = "SPECIAL",
            .tip      = "Shimmering shoegaze — Scotch flutter, long echo, wide body",
            .tape_formula   = 2,
            .speed          = 2,
            .saturation_drive   = 1.5f,
            .saturation_drive_r = 1.5f,
            .wow_flutter    = 1.8f,
            .bass_db        = 1.5f,
            .treble_db      = -0.5f,
            .echo_enabled   = true,
            .echo_amount    = 0.55f,
            .echo_amount_r  = 0.55f,
        },
        {
            .name     = "KRAUTROCK",
            .category = "SPECIAL",
            .tip      = "Hypnotic motorik — BASF at 9.5 IPS, gentle flutter, warm body",
            .tape_formula   = 1,
            .speed          = 1,
            .saturation_drive   = 1.4f,
            .saturation_drive_r = 1.4f,
            .wow_flutter    = 0.6f,
            .bass_db        = 1.0f,
        },
        {
            .name     = "ECHO CHAMBER",
            .category = "SPECIAL",
            .tip      = "Long tape echo atmosphere — ambient depth with warm body",
            .tape_formula   = 0,
            .speed          = 1,
            .saturation_drive   = 1.25f,
            .saturation_drive_r = 1.25f,
            .bass_db        = 1.5f,
            .treble_db      = -0.5f,
            .echo_enabled   = true,
            .echo_amount    = 0.65f,
            .echo_amount_r  = 0.6f,
        },

    }; // kPresets[]

} // namespace bc2000dl
